language: r
cache: packages

sudo: false

r_github_packages:
 - hrbrmstr/statebins
 - cttobin/ggthemr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

# safelist
branches:
  only:
  - master

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
# always build the book
# only deploy if it is merged/pushed to master (don't deploy  a PR)
  -  ./_build.sh
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./_deploy.sh; else return 0; fi'
