language: r
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files

repos:
  cran: http://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

r_github_packages:
 - cran/extracat
 - cttobin/ggthemr
 - hadley/emo
 - hrbrmstr/statebins
 - tidyverse/forcats


addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

# safelist
branches:
  only:
  - master

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  fqdn: edav.info
  github-token: $GITHUB_PAT    # Set in the settings page
  on:
    branch: master
